#include "lilia/model/magic_serializer.hpp"

#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>

#include "lilia/model/core/magic.hpp"

namespace lilia::model::magic {

namespace {

std::string uint64_to_hex(uint64_t v) {
  std::ostringstream oss;
  oss << "0x" << std::hex << std::setw(16) << std::setfill('0') << v;
  return oss.str();
}

bool write_array_u64(std::ofstream& out, const std::string& name, const std::uint64_t* data,
                     size_t n) {
  out << "static inline const std::array<std::uint64_t, " << n << "> " << name << " = {\n    ";
  for (size_t i = 0; i < n; ++i) {
    out << uint64_to_hex(data[i]);
    if (i + 1 < n) out << ", ";
    if ((i + 1) % 4 == 0) out << "\n    ";
  }
  out << "\n};\n\n";
  return out.good();
}

bool write_array_u8(std::ofstream& out, const std::string& name, const uint8_t* data, size_t n) {
  out << "static inline const std::array<uint8_t, " << n << "> " << name << " = {\n    ";
  for (size_t i = 0; i < n; ++i) {
    out << static_cast<unsigned>(data[i]);
    if (i + 1 < n) out << ", ";
    if ((i + 1) % 16 == 0) out << "\n    ";
  }
  out << "\n};\n\n";
  return out.good();
}

bool write_table_u64_vec(std::ofstream& out, const std::string& name,
                         const std::vector<bb::Bitboard>* tables, size_t nTables) {
  out << "static inline const std::array<std::vector<std::uint64_t>, " << nTables << "> " << name
      << " = {\n";
  out << "    {\n";
  for (size_t i = 0; i < nTables; ++i) {
    const auto& vec = tables[i];
    out << "        std::vector<std::uint64_t>{";
    for (size_t j = 0; j < vec.size(); ++j) {
      out << uint64_to_hex(vec[j]);
      if (j + 1 < vec.size()) out << ", ";
    }
    out << "}";
    if (i + 1 < nTables)
      out << ",\n";
    else
      out << "\n";
  }
  out << "    }\n};\n\n";
  return out.good();
}

}  // namespace

bool serialize_magics_to_header(const std::string& outPath, const std::string& prefix) {
  // Ensure internal tables are available by referencing them through API accessors.
  const auto& rookMasks = rook_masks();
  const auto& bishopMasks = bishop_masks();

  // Attempt to call those getters:
  extern const std::array<Magic, 64>& rook_magics();
  extern const std::array<Magic, 64>& bishop_magics();
  extern const std::array<std::vector<bb::Bitboard>, 64>& rook_tables();
  extern const std::array<std::vector<bb::Bitboard>, 64>& bishop_tables();

  const auto& rmag = rook_magics();
  const auto& bmag = bishop_magics();
  const auto& rtab = rook_tables();
  const auto& btab = bishop_tables();

  std::ofstream out(outPath, std::ios::out | std::ios::trunc);
  if (!out.is_open()) return false;

  out << "#pragma once\n\n";
  out << "#include <array>\n#include <vector>\n#include <cstdint>\n\n";
  out << "// Generated magic constants & attack tables\n";
  out << "// Generated by magic_serializer - include this header instead of runtime generating "
         "magics\n\n";
  out << "namespace lilia::magic::constants {\n\n";

  // write rook magics (magic + shift)
  out << "struct MagicEntry { std::uint64_t magic; uint8_t shift; };\n\n";

  out << "static inline const std::array<MagicEntry, 64> " << prefix << "_rook_magic = {\n    {";
  for (size_t i = 0; i < 64; ++i) {
    out << "{ " << uint64_to_hex(rmag[i].magic) << ", " << static_cast<unsigned>(rmag[i].shift)
        << " }";
    if (i + 1 < 64) out << ", ";
    if ((i + 1) % 4 == 0) out << "\n    ";
  }
  out << "\n    }\n};\n\n";

  out << "static inline const std::array<MagicEntry, 64> " << prefix << "_bishop_magic = {\n    {";
  for (size_t i = 0; i < 64; ++i) {
    out << "{ " << uint64_to_hex(bmag[i].magic) << ", " << static_cast<unsigned>(bmag[i].shift)
        << " }";
    if (i + 1 < 64) out << ", ";
    if ((i + 1) % 4 == 0) out << "\n    ";
  }
  out << "\n    }\n};\n\n";

  // write rook tables
  out << "// rook attack tables\n";
  out << "static inline const std::array<std::vector<std::uint64_t>, 64> " << prefix
      << "_rook_table = {\n    {\n";
  for (size_t i = 0; i < 64; ++i) {
    out << "        std::vector<std::uint64_t>{";
    const auto& vec = rtab[i];
    for (size_t j = 0; j < vec.size(); ++j) {
      out << uint64_to_hex(vec[j]);
      if (j + 1 < vec.size()) out << ", ";
    }
    out << "}";
    if (i + 1 < 64)
      out << ",\n";
    else
      out << "\n";
  }
  out << "    }\n};\n\n";

  out << "// bishop attack tables\n";
  out << "static inline const std::array<std::vector<std::uint64_t>, 64> " << prefix
      << "_bishop_table = {\n    {\n";
  for (size_t i = 0; i < 64; ++i) {
    out << "        std::vector<std::uint64_t>{";
    const auto& vec = btab[i];
    for (size_t j = 0; j < vec.size(); ++j) {
      out << uint64_to_hex(vec[j]);
      if (j + 1 < vec.size()) out << ", ";
    }
    out << "}";
    if (i + 1 < 64)
      out << ",\n";
    else
      out << "\n";
  }
  out << "    }\n};\n\n";

  out << "} // namespace lilia::magic::constants\n";

  out.close();
  return true;
}

}  // namespace lilia::model::magic
