name: Windows Release
on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure (MSVC, Release, perf on)
        run: >
          cmake -S . -B build
          -G "Visual Studio 17 2022" -A x64
          -DCMAKE_BUILD_TYPE=Release
          -DLILIA_NATIVE=ON -DLILIA_FAST_MATH=ON -DLILIA_LTO=ON

      - name: Build both executables
        run: cmake --build build --config Release --target lilia_app lilia_engine

      - name: Verify built EXEs exist
        shell: pwsh
        run: |
          Get-ChildItem build\bin\Release\*.exe -Recurse | Format-Table FullName
          if (-not (Test-Path build\bin\Release\lilia_app.exe))    { throw "lilia_app.exe missing" }
          if (-not (Test-Path build\bin\Release\lilia_engine.exe)) { throw "lilia_engine.exe missing" }
          if (-not (Test-Path build\bin\Release\assets))           { throw "assets/ missing" }

      - name: Create release ZIP from runtime folder
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force dist | Out-Null
          Copy-Item -Recurse -Force build\bin\Release\* dist\
          Compress-Archive -Path dist\* -DestinationPath ChessEngine_Lilia-Windows.zip
          Get-ChildItem *.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-zip
          path: ChessEngine_Lilia-Windows.zip

  release:
    needs: build-windows
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with: { name: windows-zip, path: . }
      - uses: softprops/action-gh-release@v2
        with:
          files: ChessEngine_Lilia-Windows.zip
